### PR TITLE
Better 'collaborate' image

### PR DESCRIPTION
**Pull request by apahim**
Signed-off-by: Amador Pahim <apahim@redhat.com>

### CODE REVIEW

**Comment by apahim** [comment]
It's from the github profile: https://github.com/apahim.
Means 'the collaboration amount' :)

**Comment by lmr** [comment]
As much as I liked the wits of the idea, the image is not very descriptive.

**Comment by lmr** [comment]
As a suggestion, this

https://thenounproject.com/term/collaboration/28324/

Could be tried.

**Comment by apahim** [comment]
For that image we have 2 options: pay for it or use this version with credits in it:

noun_28324_cc

What do you think?

**Comment by lmr** [comment]
I wonder if there's an option to just put the same note in the website, not in the image itself.

**Comment by apahim** [comment]
They don't offer such option...

**Comment by apahim** [comment]
Wait, double checking, there's a term where they allow to use the image with the citation apart. Updating the PR.

**Pull request closed without merging**
