### PR TITLE
New site theme

### PR DESCRIPTION
**Pull request by apahim**
Signed-off-by: Amador Pahim <apahim@redhat.com>

### CODE REVIEW

**Comment by lmr** [comment]
It's hard for me to review this, I'm just going to merge it.

**Comment by lmr** [comment]
Nope, not working (screenshot attached).
screenshot from 2016-02-02 14-57-11

**Comment by lmr** [comment]
I'm going to revert it.

**Comment by clebergnu** [comment]
@lmr yep, I'm not sure @apahim intended this to be merged *right now*.

**Comment by clebergnu** [comment]
@lmr it was probably an experiment / RFC.

**Comment by lmr** [comment]
@clebergnu I guess we need screenshots and some testing (although I don't remember how to actually test those changes).

**Comment by clebergnu** [comment]
@lmr TBH, me neither!

**Comment by adereis** [comment]
just checkout the branch/commit and open index.html in your browser.

**Comment by clebergnu** [comment]
@adereis I was thinking about some sort of automated test (X/HTML, CSS syntax checking, etc). Checking it out is well, obvious... :smile:

**Comment by adereis** [comment]
OK, I feel relieved now. ;-)

I think this is not really necessary. It's a very simple page, testing it with automated tools would be overkill. But the reviewer is supposed to checkout and check it manually.

**Pull request merged**
